project:
  type: website
  output-dir: docs
  
website:
  title: "Samantha Ross"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - books.qmd
      - resume.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    page-layout: full

editor: visual

